apiVersion: v1
kind: Pod
metadata:
  labels:
    run: csv-to-json
  name: csv-to-json
spec:
    containers:
    - image: gauravkhedekar/csv-to-json
      imagePullPolicy: Always
      name: csv-to-json
