apiVersion: v1
kind: Service
metadata:
  labels:
    run: csv-to-json
  name: csv-to-json-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30080
    targetPort: 3000
  type: NodePort
  selector:
    run: csv-to-json
  sessionAffinity: None
status:
  loadBalancer: {}
